const dataPopularHotel = [
  {
    id: 1,
    imageGeneral: "",
    image: [
      {
        id: 1,
        img: "",
      },
    ],
    title: "Oydin Plaza Hotel",
    address: "Namangan ",
    descr: "lorem ipsum dolor sit amet",
    category: "Holel",
    price: 70,
    discount: 10,
    view: "Exsellent",
    viewNumber: 8,
    person: 1,
    beds: 2,
    bathroom: 1,
  },
  {
    id: 2,
    imageGeneral: "",
    image: [
      {
        id: 1,
        img: "https://images.unsplash.com/photo-1682685797208-c741d58c2eff?ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
      },
    ],
    title: "Oydin Plaza Hotel",
    address: "Namangan ",
    descr: "lorem ipsum dolor sit amet",
    category: "Holel",
    price: 80,
    discount: 10,
    view: "Exsellent",
    viewNumber: 8,
    person: 1,
    beds: 2,
    bathroom: 1,
  },
  {
    id: 3,
    imageGeneral: "",
    image: [
      {
        id: 1,
        img: "",
      },
    ],
    title: "Oydin Plaza Hotel",
    address: "Namangan ",
    descr: "lorem ipsum dolor sit amet",
    category: "Holel",
    price: 60,
    discount: 10,
    view: "Exsellent",
    viewNumber: 8,
    person: 1,
    beds: 2,
    bathroom: 1,
  },
  {
    id: 4,
    imageGeneral: "",
    image: [
      {
        id: 1,
        img: "",
      },
    ],
    title: "Oydin Plaza Hotel",
    address: "Namangan ",
    descr: "lorem ipsum dolor sit amet",
    category: "Holel",
    price: 88,
    discount: 10,
    view: "Exsellent",
    viewNumber: 8,
    person: 1,
    beds: 2,
    bathroom: 1,
  },
];

export default dataPopularHotel;
